name: Deploy to Vercel

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          REACT_APP_GROQ_KEY: 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
        run: vercel deploy --prod --token=$VERCEL_TOKEN --build-env REACT_APP_GROQ_KEY=$REACT_APP_GROQ_KEY
